[System]
ComputerName = "WINFORGE-PC"
Locale = "en-US"
Timezone = "AU"
DisableWindowsStore = true
DisableOneDrive = true
DisableCopilot = true
DisableWindowsRecall = true
DisableRemoteDesktop = true
DisableSetupDevicePrompt = true
LanguagePacks = ["en-US", "en-GB"]

[Activation]
ProductKey = "VK7JG-NPHTM-C97JM-9MPGT-3V66T"
Version = "Pro"

[Applications]
PackageManager = "winget" # Winget or Chocolatey
Install = ["7zip", "firefox", "vscode", "nodejs"]
Uninstall = ["7zip", "MSEdge"]
RemoveBloatware = true

[EnvironmentVariables]
# Setting environment variables for the user scope
User = [
    {VariableName = "TestUserVar", Value = "TestUserVarValue"},
    {VariableName = "TestUserVar2", Value = "TestUserVar2Value"}
]

# Setting environment variables for the system scope
System = [
    {VariableName = "CompanyName", Value = "Zebra Corp"},
    {VariableName = "Department", Value = "Stripes"}
]


[Explorer]
ShowFileExtensions = true
ShowHiddenFolders = true

[Taskbar]
TaskbarAlignment = "Left" # Left or Center
DisableMeetNow = true
DisableWidgets = true
DisableTaskView = true
DisableSearch = true

[Theme]
DarkMode = true
DesktopIconSize = "Medium" # Small, Medium, Large
WallpaperPath = "https://images.pexels.com/photos/2085998/pexels-photo-2085998.jpeg"
LockScreenPath = "https://images.pexels.com/photos/2341830/pexels-photo-2341830.jpeg"
DisableTransparencyEffects = true
DisableWindowsAnimations = true
DisableTransparency = true

[Tweaks]
ClassicRightClickMenu = true
GodModeFolder = true

[Power]
PowerPlan = "Balanced"
AllowSleep = true
AllowHibernate = true
DisableFastStartup = true
MonitorTimeout = 15 # minutes (integer)
SleepTimeout = 30 # minutes (integer)
HibernateTimeout = 60 # minutes (integer)

[Network]
AllowNetworkDiscovery = true
AllowFileAndPrinterSharing = true
MapNetworkDrive = [
    {DriveLetter = "S", Path = "\\\\192.168.0.10\\Media", User = "Administrator", Password = "Password123"},
    {DriveLetter = "T", Path = "\\\\192.168.0.10\\Media", User = "Administrator", Password = "Password123"}
]


[Privacy]
DisableTelemetry = true
DisableDiagTrack = true
DisableAppPrivacy = true
DisablePersonalisedAdvertising = true
DisableStartMenuTracking = true
DisableActivityHistory = true
DisableClipboardDataCollection = true
DisableStartMenuSuggestions = true
DisableDiagnosticData = true
DisableWindowsRecall = true

[Fonts]
Font = ["roboto", "opensans", "lato", "firasans"]


[Google]
# Google Drive configuration
Drive = [
    {Install = true},
    {DefaultWebBrowser = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"},
    {DisableOnboardingDialog = true},
    {DisablePhotosSync = true},
    {AutoStartOnLogin = true},
    {OpenOfficeFilesInDocs = true}
]

# Chrome configuration
Chrome = [
    {Install = true},
    {CloudManagementEnrollmentToken = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
    {AlwaysOpenPdfExternally = true},
    {BrowserSignin = 2} #0 = Disable browser sign-in, 1 = Enable browser sign-in, 2 = Force users to sign-in to use the browser
]

GCPW = [
    {Install = true},
    {EnrollmentToken = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
    {DomainsAllowedToLogin = "example.com"}
]

[Security]
DisableAutoPlay = true
UAC = {Enable = true, Level = "NotifyChanges"}  # Options: "AlwaysNotify", "NotifyChanges", "NotifyNoDesktop", "NeverNotify"

# Windows Defender Configuration - More granular control
[WindowsDefender]
RealTimeProtection = true
CloudProtection = true
AutomaticSampleSubmission = false
NetworkProtection = true
ControlledFolderAccess = false
AttackSurfaceReduction = true
ExclusionPaths = ["C:\\MyApp\\", "C:\\Temp\\"]
ExclusionExtensions = [".tmp", ".log"]
ExclusionProcesses = ["myapp.exe", "backup.exe"]
ScanSettings = {
    QuickScanTime = "02:00",  # 2 AM daily quick scan
    FullScanDay = "Sunday",   # Weekly full scan on Sunday
    ScanRemovableDrives = true,
    ScanArchives = true,
    ScanNetworkFiles = false
}
ThreatSettings = {
    DefaultAction = "Quarantine",  # Options: "Clean", "Quarantine", "Remove", "Allow", "UserDefined", "Block"
    SubmitSamplesConsent = "SendSafeSamples",  # Options: "AlwaysPrompt", "SendSafeSamples", "NeverSend", "SendAllSamples"
    MAPSReporting = "Advanced"  # Options: "Disabled", "Basic", "Advanced"
}

[WindowsUpdate]
EnableAutomaticUpdates = true
AUOptions = 3 # 0 = Automatic, 1 = Notify, 2 = NotifyChanges, 3 = NotifyChangesAndRestart, 4 = NotifyChangesAndRestartIfRequired
AutoInstallMinorUpdates = true
ScheduledInstallDay = 1 # 1-7 (Monday-Sunday)
ScheduledInstallTime = 3 # 0-23 (0 = 12:00 AM, 23 = 11:00 PM)

[WindowsFeatures]
Enable = [
  "Microsoft-Hyper-V-All",
  "Containers-DisposableClientVM",
  "Microsoft-RemoteDesktopConnection",
  "VirtualMachinePlatform"
]

Disable = [
  "Containers-DisposableClientVM"
]



[Office]
LicenseKey = "NMMKJ-6RK4F-KMJVX-8D9MJ-6MWKP"
ProductID = "ProPlus2019Retail" # ProPlus2019Retail, ProPlus2021Retail, ProPlus2021Volume, ProPlus2021VolumeRetail, ProPlus2021SemiAnnualRetail, ProPlus2021SemiAnnual
LanguageID = "en-US"
DisplayLevel = "None"
SetupReboot = "Never" # Never, Always
Channel = "SemiAnnual" # SemiAnnual, MonthlyEnterprise, Monthly, MonthlyRetail
OfficeClientEdition = 64 # 32, 64
UpdatesEnabled = true

[Registry]

Add = [
    {Name = "DisableLockScreenAppNotifications", Path = "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System", Type = "DWord", Value = 1, Description = "Disable lock screen app notifications"},
    {Name = "DefaultWebBrowser", Path = "HKLM:\\SOFTWARE\\Google\\DriveFS", Type = "String", Value = "$env:SystemDrive\\Program Files\\Google\\Chrome\\Application\\chrome.exe", Description = "Set default web browser for Google Drive"},
    {Name = "DisableTaskMgr", Path = "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System", Type = "DWord", Value = 1}
]

Remove = [
    { Name = "DisableLockScreenAppNotifications", Path = "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System"},
    { Name = "DisableTaskMgr", Path = "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System"}
]
 
[Tasks]
Add = [
    {Name = "AutoShutdown", Path = "https://raw.githubusercontent.com/Graphixa/WinforgeX/main/Tasks/AutoShutdown.xml", Description = "Auto Shutdown"},
    {Name = "Task2", Path = "C:\\Tasks\\Task2.xml", Description = "Task 2"},
    {Name = "Task3", Path = "C:\\Tasks\\Task3.xml", Description = "Task 3"}
]

Remove = [
    {Name = "Task2", Description = "Task 2"},
    {Name = "Task3", Description = "Task 3"}
]

AddRepository = "https://github.com/Graphixa/Winforge/tree/main/Tasks/"


[Commands]

Run = [
    {Program = "calc.exe", Arguments = ""},
    {Program = "cmd.exe", Arguments = "/c echo Hello, World!"}
]

Cmd = [
    {Command = "echo Hello, World! && pause"}
]

Powershell = [
    {Command = "echo Hello, World!"},
    {Command = "New-Item -Path C:\\Temp\\test.txt -ItemType File -Value 'Hello, World!'"}
]

[FileOperations]
Copy = [
    { Source = "\\\\server\\share\\file.txt", Destination = "$env:USERPROFILE\\Documents\\file.txt" },
    { Source = "\\\\server\\share\\data.csv", Destination = "C:\\Reports\\data.csv" },
    { Source = "\\\\server\\share\\configs", Destination = "C:\\ProgramData\\App\\configs" }
]

Move = [
    { Source = "C:\\Temp\\file.txt", Destination = "D:\\Temp\\file.txt" },
    { Source = "C:\\Temp\\folder", Destination = "D:\\Backup\\folder" }
]

Rename = [
    { Source = "C:\\Temp\\oldname.txt", NewName = "C:\\Temp\\newname.txt" },
    { Source = "C:\\Temp\\oldfolder", NewName = "C:\\Temp\\newfolder" }
]

New = [
    { Type = "File", Path = "C:\\Temp\\newfile.txt" },
    { Type = "Folder", Path = "C:\\Temp\\newfolder" }
]

Delete = [
    { Path = "C:\\Temp\\oldfolder" },
    { Path = "C:\\Temp\\oldfile.txt" },
    { Path = "C:\\Users\\Public\\Logs" }
]

Shortcut = [
    # Iconpath is optional, if not specified, the default icon will be used
    { Name = "Google Chrome", Target = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", Location = "Desktop", Arguments = "--profile-directory=Default", IconPath = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe,0", WorkingDirectory = "C:\\Program Files\\Google\\Chrome\\Application" },
    { Name = "Notepad", Target = "notepad.exe", Location = "StartMenu", Arguments = "", IconPath = "notepad.exe,0", WorkingDirectory = "" }
]


